# ============================================================
# deploy.ps1 - Script de deployment para Atinet Compliance Hub
# Uso: .\deploy.ps1
# ============================================================

# Continue: los procesos externos (git, composer, npm) escriben a stderr de forma informativa.
# Verificamos errores reales mediante $LASTEXITCODE después de cada comando.
$ErrorActionPreference = "Continue"
$startTime = Get-Date

function Write-Step {
    param([int]$num, [int]$total, [string]$msg)
    Write-Host ""
    Write-Host "  [$num/$total] $msg" -ForegroundColor Cyan
}

function Write-OK   { param([string]$msg) Write-Host "  OK  $msg" -ForegroundColor Green }
function Write-Warn { param([string]$msg) Write-Host "  WARN  $msg" -ForegroundColor Yellow }
function Write-Fail { param([string]$msg) Write-Host "  FAIL  $msg" -ForegroundColor Red }

Write-Host ""
Write-Host "======================================================" -ForegroundColor Magenta
Write-Host "   ATINET COMPLIANCE HUB - DEPLOYMENT $(Get-Date -Format 'dd/MM/yyyy HH:mm')" -ForegroundColor Magenta
Write-Host "======================================================" -ForegroundColor Magenta

Set-Location $PSScriptRoot

# ----------------------------------------------------------
# 1. Git pull
# ----------------------------------------------------------
Write-Step 1 7 "Obteniendo cambios desde GitHub..."
try {
    # Archivos generados automáticamente que se pueden descartar sin riesgo
    $autoGenerated = @(
        "bootstrap/cache/packages.php",
        "bootstrap/cache/services.php",
        "package-lock.json"
    )
    foreach ($f in $autoGenerated) {
        if (Test-Path $f) {
            git checkout -- $f 2>$null
        }
    }
    # Se respaldan, se retiran temporalmente para que git pueda hacer merge, y se restauran
    $serverFiles = @("public/web.config")
    $backups = @{}
    foreach ($f in $serverFiles) {
        if (Test-Path $f) {
            $backups[$f] = Get-Content $f -Raw -Encoding UTF8
            Remove-Item $f -Force
            Write-Host "     Respaldado: $f" -ForegroundColor Gray
        }
    }

    # git escribe mensajes informativos a stderr; los suprimimos con 2>$null y controlamos errores por $LASTEXITCODE
    git pull origin master 2>$null
    $gitExitCode = $LASTEXITCODE

    if ($gitExitCode -ne 0) {
        # Ejecutar de nuevo para capturar el error real
        $errDetail = git pull origin master 2>&1 | Where-Object { $_ -match "error:|fatal:" } | Select-Object -First 3
        throw ($errDetail -join "`n")
    }

    # Restaurar archivos del servidor (tienen prioridad sobre lo que vino del repo)
    foreach ($f in $backups.Keys) {
        Set-Content $f $backups[$f] -Encoding UTF8 -NoNewline
        Write-Host "     Restaurado: $f" -ForegroundColor Gray
    }

    Write-OK "Git pull completado"
} catch {
    Write-Fail "Git pull falló: $_"
    exit 1
}

# ----------------------------------------------------------
# 2. Composer
# ----------------------------------------------------------
Write-Step 2 7 "Instalando dependencias PHP (composer)..."
try {
    composer install --no-dev --optimize-autoloader --quiet
    if ($LASTEXITCODE -ne 0) { throw "composer install falló" }
    Write-OK "Dependencias PHP instaladas"
} catch {
    Write-Fail "$_"
    exit 1
}

# ----------------------------------------------------------
# 3. NPM + Build
# ----------------------------------------------------------
Write-Step 3 7 "Compilando assets frontend (npm)..."
try {
    npm install --legacy-peer-deps --silent --no-audit --no-fund 2>$null
    if ($LASTEXITCODE -ne 0) { throw "npm install falló" }
    $buildLog = [System.IO.Path]::GetTempFileName()
    npm run build > $buildLog 2>&1
    $npmExitCode = $LASTEXITCODE
    Remove-Item $buildLog -Force -ErrorAction SilentlyContinue
    if ($npmExitCode -ne 0) { throw "npm run build falló (código $npmExitCode)" }
    Write-OK "Assets compilados correctamente"
} catch {
    Write-Fail "$_"
    exit 1
}

# ----------------------------------------------------------
# 4. Limpiar cachés
# ----------------------------------------------------------
Write-Step 4 7 "Limpiando cachés de Laravel..."
php artisan optimize:clear --quiet
Write-OK "Cachés limpiadas"

# ----------------------------------------------------------
# 5. Migraciones
# ----------------------------------------------------------
Write-Step 5 7 "Ejecutando migraciones de base de datos..."
try {
    $migrateOutput = php artisan migrate --force 2>&1
    if ($LASTEXITCODE -ne 0) { throw $migrateOutput }
    Write-OK "Migraciones ejecutadas"
} catch {
    Write-Fail "Migraciones fallaron: $_"
    exit 1
}

# ----------------------------------------------------------
# 6. Cachear configuración
# ----------------------------------------------------------
Write-Step 6 7 "Cacheando configuración, rutas y vistas..."
php artisan config:cache --quiet
php artisan route:cache --quiet
php artisan view:cache  --quiet
Write-OK "Configuración cacheada"

# ----------------------------------------------------------
# 7. Reiniciar queue workers
# ----------------------------------------------------------
Write-Step 7 7 "Reiniciando queue workers..."
php artisan queue:restart --quiet 2>$null
Write-OK "Queue workers notificados"

# ----------------------------------------------------------
# HEALTH CHECK
# ----------------------------------------------------------
Write-Host ""
Write-Host "------------------------------------------------------" -ForegroundColor DarkGray
Write-Host "  VERIFICACION DEL SITIO" -ForegroundColor White
Write-Host "------------------------------------------------------" -ForegroundColor DarkGray

$allPassed = $true

# --- 1. Verificaciones PHP/Laravel directas (no dependen de IIS) ---
Write-Host ""
Write-Host "  Laravel:" -ForegroundColor Gray

# Rutas cacheadas o disponibles
$routeCount = (php artisan route:list 2>$null | Measure-Object -Line).Lines
if ($routeCount -gt 5) {
    Write-OK "Rutas disponibles ($routeCount definidas)"
} else {
    Write-Fail "Rutas insuficientes (solo $routeCount)"
    $allPassed = $false
}

# Configuración válida
php artisan config:show app.name 2>$null | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-OK "Configuracion de Laravel valida"
} else {
    Write-Fail "Problemas con configuracion de Laravel"
    $allPassed = $false
}

# Conexion a base de datos
php artisan migrate:status > $null 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-OK "Conexion a base de datos OK"
} else {
    Write-Fail "No se puede conectar a la base de datos"
    $allPassed = $false
}

# --- 2. Verificacion HTTP ---
$appUrl = "http://localhost"
if (Test-Path ".env") {
    $envLine = Get-Content ".env" | Where-Object { $_ -match "^APP_URL=" } | Select-Object -First 1
    if ($envLine) { $appUrl = $envLine -replace "^APP_URL=", "" }
}

Write-Host ""
Write-Host "  HTTP ($appUrl):" -ForegroundColor Gray

$httpChecks = @(
    @{ Name = "Raiz del sitio";  Url = "$appUrl/";      ExpectedCode = @(200, 302, 301, 403) },
    @{ Name = "Login";           Url = "$appUrl/login";  ExpectedCode = @(200, 302, 301, 404) }
)

foreach ($check in $httpChecks) {
    try {
        $response = Invoke-WebRequest -Uri $check.Url -UseBasicParsing -TimeoutSec 8 -MaximumRedirection 0 -ErrorAction SilentlyContinue
        $code = $response.StatusCode
    } catch {
        $code = if ($_.Exception.Response) { [int]$_.Exception.Response.StatusCode } else { 0 }
    }

    if ($code -eq 0) {
        Write-Fail "$($check.Name) - Sin respuesta (servidor caido?)"
        $allPassed = $false
    } elseif ($check.ExpectedCode -contains $code) {
        Write-OK "$($check.Name) (HTTP $code)"
    } else {
        Write-Fail "$($check.Name) - HTTP $code inesperado"
        $allPassed = $false
    }
}

# Verificar que no haya errores recientes en el log de Laravel
Write-Host ""
$logPath = "storage\logs\laravel.log"
if (Test-Path $logPath) {
    $recentErrors = Get-Content $logPath -Tail 50 | Where-Object { $_ -match "\[ERROR\]|\[CRITICAL\]|\[ALERT\]|\[EMERGENCY\]" }
    if ($recentErrors.Count -gt 0) {
        Write-Warn "Se encontraron $($recentErrors.Count) errores recientes en laravel.log:"
        $recentErrors | Select-Object -Last 3 | ForEach-Object {
            Write-Host "     $_" -ForegroundColor Yellow
        }
    } else {
        Write-OK "Sin errores criticos en laravel.log"
    }
} else {
    Write-Warn "No se encontro archivo de log"
}

# ----------------------------------------------------------
# RESUMEN FINAL
# ----------------------------------------------------------
$elapsed = [math]::Round(((Get-Date) - $startTime).TotalSeconds, 1)
Write-Host ""
Write-Host "======================================================" -ForegroundColor Magenta

if ($allPassed) {
    Write-Host "  DEPLOYMENT EXITOSO en $($elapsed)s" -ForegroundColor Green
} else {
    Write-Host "  DEPLOYMENT COMPLETADO CON ADVERTENCIAS ($($elapsed)s)" -ForegroundColor Yellow
    Write-Host "  Revisa los errores anteriores antes de continuar." -ForegroundColor Yellow
}

Write-Host "======================================================" -ForegroundColor Magenta
Write-Host ""
