name: Deploy AWS Production

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
              cd /var/www/atinet-app

              echo "=== VERIFICANDO REPOSITORIO ==="

              pwd

              git status

              git branch

              echo "=== FIN ==="
