name: Deploy AWS Production

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "=== PRUEBA SSH ==="

            whoami

            hostname

            pwd

            echo "Conexion exitosa"
